<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import { createApiClient } from '../api/client'; import { createIdempotencyKey } from '../api/idempotency'; import type { ChatMessage } from '../api/contracts'
const route=useRoute(); const client=createApiClient(); const messages=ref<ChatMessage[]>([]); const text=ref(''); const loading=ref(true); const loadingMore=ref(false); const hasMore=ref(false); const nextCursor=ref<string|null>(null); const error=ref(''); const sendError=ref(''); const quick=['我已确认费用分摊','预计准时到达','请发一下上车点']
async function load(){loading.value=true;error.value='';try{const page=await client.listMessagesPage(String(route.params.id));messages.value=page.messages;hasMore.value=page.hasMore;nextCursor.value=page.nextCursor}catch(caught){error.value=caught instanceof Error?caught.message:'消息加载失败，请重试'}finally{loading.value=false}}
async function loadMore(){if(!hasMore.value||!nextCursor.value)return;loadingMore.value=true;try{const page=await client.listMessagesPage(String(route.params.id),{before:nextCursor.value,limit:30});messages.value=[...page.messages,...messages.value];hasMore.value=page.hasMore;nextCursor.value=page.nextCursor}catch(caught){error.value=caught instanceof Error?caught.message:'历史消息加载失败'}finally{loadingMore.value=false}}
async function send(){if(!text.value.trim()){sendError.value='消息不能为空';return}sendError.value='';try{messages.value.push(await client.sendMessage(String(route.params.id),text.value.trim(),createIdempotencyKey()));text.value=''}catch(caught){sendError.value=caught instanceof Error?caught.message:'发送失败，请稍后重试'}}
onMounted(load)
</script>
<template><main class="page"><div class="eyebrow">同行沟通</div><h1>聊天</h1><div v-if="loading" class="async-state">正在加载消息…</div><div v-else-if="error" class="async-state state-error" role="alert">{{error}} <button class="secondary-button" @click="load">重新加载</button></div><template v-else><button v-if="hasMore" class="secondary-button" :disabled="loadingMore" @click="loadMore">{{loadingMore?'加载中…':'加载更早消息'}}</button><div v-if="!messages.length" class="async-state">还没有消息，先打个招呼吧。</div><div v-else class="chat-list"><article v-for="m in messages" :key="m.id" class="detail-card"><p>{{m.text}}</p><small class="muted">{{new Date(m.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}}</small></article></div></template><div class="choice-row"><button v-for="q in quick" :key="q" class="secondary-button" @click="text=q">{{q}}</button></div><p v-if="sendError" class="form-error" role="alert">{{sendError}}</p><form class="chat-input" @submit.prevent="send"><input v-model="text" maxlength="500" aria-label="消息" placeholder="输入消息"/><button class="primary-button">发送</button></form><a class="text-button" href="tel:110">紧急情况拨打 110</a></main></template>
