<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import RideFallback from '../components/RideFallback.vue'; import { createApiClient } from '../api/client'; import { createIdempotencyKey } from '../api/idempotency'; import type { Trip } from '../api/contracts'
const route=useRoute(); const api=createApiClient(); const trip=ref<Trip|null>(null); const plate=ref(''); const model=ref(''); const color=ref(''); const saved=ref(false); const error=ref(''); const busy=ref(false); const launchMessage=ref('')
async function load(){try{trip.value=await api.getTrip(String(route.params.id))}catch(caught){error.value=caught instanceof Error?caught.message:'行程加载失败'}}
async function save(){if(!plate.value.trim())return;busy.value=true;error.value='';try{await api.updateVehicle(String(route.params.id),{plate:plate.value.trim(),model:model.value.trim()||undefined,color:color.value.trim()||undefined},createIdempotencyKey());saved.value=true}catch(caught){error.value=caught instanceof Error?caught.message:'车辆信息保存失败，请重试'}finally{busy.value=false}}
async function openRide(){busy.value=true;error.value='';try{const result:any=await api.openRide(String(route.params.id),'manual',createIdempotencyKey());launchMessage.value=result?.launch?.supported?'已打开叫车平台':'平台暂未接入，请复制路线后手动叫车'}catch(caught){error.value=caught instanceof Error?caught.message:'叫车准备失败，请重试'}finally{busy.value=false}}
onMounted(load)
</script>
<template><main class="page"><div class="eyebrow">出行准备</div><h1>车辆信息</h1><div v-if="error" class="form-error" role="alert">{{error}}</div><div class="detail-card"><p>请先阅读：同路行不提供司机端、实时定位或自动行车守护。车辆信息仅用于同行识别。</p><label>车牌号<input v-model="plate" required placeholder="粤A·12345" /></label><label>车型（可选）<input v-model="model" placeholder="如：轿车" /></label><label>颜色（可选）<input v-model="color" placeholder="如：白色" /></label><button class="primary-button" :disabled="busy || !plate.trim()" @click="save">{{saved?'已保存':'保存车辆信息'}}</button><button class="secondary-button" :disabled="busy || !saved" @click="openRide">准备叫车</button><p v-if="launchMessage" class="muted" role="status">{{launchMessage}}</p></div><RideFallback :text="trip ? `${trip.origin} → ${trip.destination}` : '行程路线加载中，请稍后重试'" /></main></template>
