<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { showToast } from 'vant'; import { createApiClient } from '../api/client'; import { createIdempotencyKey } from '../api/idempotency'; import type { Trip } from '../api/contracts'; import JoinSheet from '../components/JoinSheet.vue'; import ConfirmationPanel from '../components/ConfirmationPanel.vue'; import { useSessionStore } from '../stores/session'
const route = useRoute(); const router = useRouter(); const session = useSessionStore(); const client = createApiClient(); const trip = ref<Trip | null>(null); const loading = ref(true); const error = ref(''); const open = ref(false); const busy = ref(false); const joinError = ref('');
const remaining = computed(() => trip.value ? trip.value.capacity - trip.value.activeMemberCount : 0)
async function load() { loading.value = true; error.value = ''; try { trip.value = await client.getTrip(String(route.params.id)) } catch (caught) { error.value = caught instanceof Error ? caught.message : '加载失败' } finally { loading.value = false } }
async function join(count: 1 | 2) { if (!session.user) { await router.push({ name: 'login', query: { redirect: `/trips/${encodeURIComponent(String(route.params.id))}` } }); return }; busy.value = true; joinError.value = ''; try { await client.joinTrip(String(route.params.id), { memberCount: count }, createIdempotencyKey()); open.value = false; showToast('申请已提交，等待发单人接受') } catch (caught) { joinError.value = caught instanceof Error ? caught.message : '申请失败'; if ((caught as { status?: number }).status === 409) await load() } finally { busy.value = false } }
async function confirm() { if (trip.value) trip.value = await client.confirmTrip(trip.value.id, createIdempotencyKey()) }
async function withdraw() { if (trip.value?.confirmationId) trip.value = await client.withdrawConfirmation(trip.value.id, trip.value.confirmationId, createIdempotencyKey()) }
onMounted(load)
</script>
<template><main class="page"><div v-if="loading" class="async-state">正在加载行程…</div><div v-else-if="error" class="async-state state-error" role="alert"><p>{{ error }}</p><button class="secondary-button" @click="load">重新加载</button></div><template v-else-if="trip"><div class="eyebrow">行程详情</div><h1>{{ trip.origin }} → {{ trip.destination }}</h1><div class="detail-card"><p class="detail-time">{{ new Date(trip.departureAt).toLocaleString('zh-CN') }}</p><p>当前同行：{{ trip.activeMemberCount }}/{{ trip.capacity }} 人 · 还剩 {{ remaining }} 个席位</p><p class="muted">推荐依据：{{ trip.recommendationReasons.map(r => ({ TIME_CLOSE: '时间相近', RELIABLE: '履约较好', VERIFIED: '已验证', AVAILABLE: '空位充足' } as Record<string,string>)[r]).filter(Boolean).slice(0,3).join('、') || '暂无' }}</p></div><ConfirmationPanel v-if="trip.status !== 'CANCELLED' && trip.status !== 'EXPIRED'" :status="trip.status" :confirmed-count="trip.confirmedCount ?? 0" :total="trip.capacity" :retract-until="trip.retractUntil" @confirm="confirm" @withdraw="withdraw" /><button class="primary-button" :disabled="remaining < 1" @click="open = true">{{ remaining ? '申请加入' : '已满员' }}</button><div class="choice-row"><RouterLink class="secondary-button" :to="`/trips/${trip.id}/chat`">聊天</RouterLink><RouterLink class="secondary-button" :to="`/trips/${trip.id}/ride`">叫车</RouterLink><RouterLink v-if="trip.fareOrderId" class="secondary-button" :to="`/orders/${trip.fareOrderId}`">订单</RouterLink><RouterLink class="secondary-button" :to="`/sos?tripId=${encodeURIComponent(trip.id)}`">安全求助</RouterLink></div><JoinSheet :open="open" :busy="busy" :error="joinError" @close="open = false" @submit="join" /></template></main></template>

